<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class DatabaseSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{

//		DB::table('categories')->insert(array(
//				array('id' => NULL, 'category_name' => "N'�����", 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
//				array('id' => NULL, 'category_name' => 'aaa', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
//		));


		DB::table('categories')->insert(array(
				array('id' => NULL, 'category_name' => 'Antiques', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Art', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Baby', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Books', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Business & Industrial', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Cameras & Photo', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Cell Phones & Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Clothing, Shoes & Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Coins & Paper Money', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Collectibles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Computers/Tablets & Networking', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Consumer Electronics', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Crafts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Dolls & Bears', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'DVDs & Movies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Motors', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Entertainment Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Gift Cards & Coupons', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Health & Beauty', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Home & Garden', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Jewelry & Watches', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Music', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Musical Instruments & Gear', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Pet Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Pottery & Glass', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Real Estate', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Specialty Services', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Sporting Goods', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Sports Mem, Cards & Fan Shop', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Stamps', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Tickets & Experiences', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Toys & Hobbies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Travel', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Video Games & Consoles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_name' => 'Everything Else', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
		));

		DB::table('sub_categories')->insert(array(
				/* Antiques */
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Antiquities', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Architectural & Garden', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Asian Antiques', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Books & Manuscripts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Decorative Arts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Ethnographic', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Furniture', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Home & Hearth', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Linens & Textiles (Pre-1930)', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Maps, Atlases & Globes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Maritime', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Mercantile, Trades & Factories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Musical Instruments (Pre-1930)', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Periods & Styles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Primitives', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Restoration & Care', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Rugs & Carpets', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Science & Medicine (Pre-1930)', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Sewing (Pre-1930)', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Silver', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Reproduction Antiques', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '1', 'sub_category_name' => 'Other Antiques', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Art */
				array('id' => NULL, 'category_id' => '2', 'sub_category_name' => 'Direct from the Artist', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '2', 'sub_category_name' => 'Art from Dealers & Resellers', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '2', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Baby */
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Baby Gear', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Baby Safety & Health', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Bathing & Grooming', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Car Safety Seats', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Diapering', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Feeding', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Keepsakes & Baby Announcements', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Nursery Bedding', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Nursery Decor', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Nursery Furniture', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Potty Training', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Strollers', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Stroller Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Toys for Baby', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Other Baby', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '3', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Books */
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Antiquarian & Collectible', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Audiobooks', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Catalogs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Children & Young Adults', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Cookbooks', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Fiction & Literature', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Magazine Back Issues', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Nonfiction', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Textbooks, Education', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Wholesale & Bulk Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '4', 'sub_category_name' => 'Other Books', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Business & Industrial */
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Agriculture & Forestry', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Construction', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Electrical & Test Equipment', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Fuel & Energy', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Healthcare, Lab & Life Science', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Heavy Equipment', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Heavy Equipment Attachments', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Heavy Equipment Parts & Accs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Light Equipment & Tools', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Manufacturing & Metalworking', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'MRO & Industrial Supply', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Office', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Packing & Shipping', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Printing & Graphic Arts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Restaurant & Catering', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Retail & Services', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Websites & Businesses for Sale', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '5', 'sub_category_name' => 'Other Business & Industrial', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Cameras & Photo */
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Binoculars & Telescopes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Camera Drones', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Camcorders', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Digital Cameras', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Camera & Photo Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Camera & Photo Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Digital Photo Frames', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Film Photography', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Flashes & Flash Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Lenses & Filters', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Lighting & Studio', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Manuals & Guides', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Replacement Parts & Tools', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Tripods & Supports', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Video Production & Editing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Vintage Movie & Photography', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '6', 'sub_category_name' => 'Other Cameras & Photo', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Cell Phones & Accessories */
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Cell Phones & Smartphones', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Smart Watches', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Smart Watch Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Cell Phone Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Display Phones', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Phone Cards & SIM Cards', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Cell Phone & Smartphone Parts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '7', 'sub_category_name' => 'Other Cell Phones & Accs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Clothing, Shoes & Accessories */
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Baby & Toddler Clothing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Kids Clothing, Shoes & Accs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Costumes, Reenactment, Theater', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Cultural & Ethnic Clothing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Dancewear', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Mens Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Mens Clothing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Mens Shoes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Uniforms & Work Clothing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Unisex Clothing, Shoes & Accs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Wedding & Formal Occasion', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Womens Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Womens Clothing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Womens Handbags & Bags', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Womens Shoes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Vintage', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '8', 'sub_category_name' => 'Wholesale, Large & Small Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Coins & Paper Money */
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Bullion', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Coins: US', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Coins: Canada', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Coins: Ancient', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Coins: Medieval', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Coins: World', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Exonumia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Paper Money: US', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Paper Money: World', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Publications & Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Stocks & Bonds, Scripophily', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Virtual Currency', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '9', 'sub_category_name' => 'Other Coins & Paper Money', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Collectibles */
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Advertising', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Animals', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Animation Art & Characters', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Arcade, Jukeboxes & Pinball', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Autographs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Banks, Registers & Vending', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Barware', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Beads', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Bottles & Insulators', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Breweriana, Beer', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Casino', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Clocks', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Comics', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Cultures & Ethnicities', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Decorative Collectibles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Disneyana', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Fantasy, Mythical & Magic', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Historical Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Holiday & Seasonal', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Kitchen & Home', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Knives, Swords & Blades', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Lamps, Lighting', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Linens & Textiles (1930-Now)', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Metalware', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Militaria', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Paper', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Pens & Writing Instruments', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Pez, Keychains, Promo Glasses', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Photographic Images', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Pinbacks, Bobbles, Lunchboxes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Postcards', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Radio, Phonograph, TV, Phone', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Religion & Spirituality', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Rocks, Fossils & Minerals', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Science Fiction & Horror', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Science & Medicine (1930-Now)', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Sewing (1930-Now)', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Souvenirs & Travel Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Tobacciana', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Tools, Hardware & Locks', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Trading Cards', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Transportation', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Vanity, Perfume & Shaving', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Vintage, Retro, Mid-Century', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '10', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Computers/Tablets & Networking */
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'iPads, Tablets & eBook Readers', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'iPad/Tablet/eBook Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Tablet & eBook Reader Parts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Laptops & Netbooks', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Desktops & All-In-Ones', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Laptop & Desktop Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Cables & Connectors', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Computer Components & Parts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Drives, Storage & Blank Media', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Enterprise Networking, Servers', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Home Networking & Connectivity', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Keyboards, Mice & Pointing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Monitors, Projectors & Accs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Power Protection, Distribution', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Printers, Scanners & Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Software', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Manuals & Resources', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Vintage Computing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '11', 'sub_category_name' => 'Other Computers & Networking', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Consumer Electronics */
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Portable Audio & Headphones', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'TV, Video & Home Audio', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Vehicle Electronics & GPS', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Home Automation', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Home Surveillance', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Home Telephones & Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Multipurpose Batteries & Power', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Radio Communication', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Gadgets & Other Electronics', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Vintage Electronics', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '12', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Crafts */
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Art Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Beads & Jewelry Making', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Glass & Mosaics', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Handcrafted & Finished Pieces', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Home Arts & Crafts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Kids Crafts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Multi-Purpose Craft Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Needlecrafts & Yarn', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Scrapbooking & Paper Crafts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Sewing & Fabric', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Stamping & Embossing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Other Crafts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '13', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Dolls & Bears */
				array('id' => NULL, 'category_id' => '14', 'sub_category_name' => 'Bear Making Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '14', 'sub_category_name' => 'Bears', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '14', 'sub_category_name' => 'Dolls', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '14', 'sub_category_name' => 'Dollhouse Miniatures', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '14', 'sub_category_name' => 'Paper Dolls', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '14', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* DVDs & Movies */
				array('id' => NULL, 'category_id' => '15', 'sub_category_name' => 'DVDs & Blu-ray Discs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '15', 'sub_category_name' => 'Film Stock', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '15', 'sub_category_name' => 'Laserdiscs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '15', 'sub_category_name' => 'UMDs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '15', 'sub_category_name' => 'VHS Tapes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '15', 'sub_category_name' => 'Other Formats', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '15', 'sub_category_name' => 'Storage & Media Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '15', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Motors */
				array('id' => NULL, 'category_id' => '16', 'sub_category_name' => 'Cars & Trucks', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '16', 'sub_category_name' => 'Motorcycles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '16', 'sub_category_name' => 'Other Vehicles & Trailers', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '16', 'sub_category_name' => 'Boats', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '16', 'sub_category_name' => 'Powersports', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '16', 'sub_category_name' => 'Parts & Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Entertainment Memorabilia */
				array('id' => NULL, 'category_id' => '17', 'sub_category_name' => 'Autographs-Original', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '17', 'sub_category_name' => 'Autographs-Reprints', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '17', 'sub_category_name' => 'Movie Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '17', 'sub_category_name' => 'Music Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '17', 'sub_category_name' => 'Television Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '17', 'sub_category_name' => 'Theater Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '17', 'sub_category_name' => 'Video Game Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '17', 'sub_category_name' => 'Other Entertainment Mem', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Gift Cards & Coupons */
				array('id' => NULL, 'category_id' => '18', 'sub_category_name' => 'Gift Cards', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '18', 'sub_category_name' => 'eBay Gift Cards', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '18', 'sub_category_name' => 'Gift Certificates', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '18', 'sub_category_name' => 'Coupons', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '18', 'sub_category_name' => 'Digital Gifts', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Health & Beauty */
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Bath & Body', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Dietary Supplements, Nutrition', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Fragrances', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Hair Care & Styling', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Health Care', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Makeup', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Massage', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Medical, Mobility & Disability', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Nail Care, Manicure & Pedicure', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Natural & Homeopathic Remedies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Oral Care', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Over-the-Counter Medicine', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Salon & Spa Equipment', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Shaving & Hair Removal', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Skin Care', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Sun Protection & Tanning', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Tattoos & Body Art', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Vision Care', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Weight Management', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '19', 'sub_category_name' => 'Other Health & Beauty', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Home & Garden */
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Bath', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Bedding', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Food & Beverages', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Fresh Cut Flowers & Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Furniture', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Greeting Cards & Party Supply', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Holiday & Seasonal Decor', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Home Decor', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Home Improvement', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Household Supplies & Cleaning', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Kids & Teens at Home', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Kitchen, Dining & Bar', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Lamps, Lighting & Ceiling Fans', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Major Appliances', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Rugs & Carpets', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Tools', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Wedding Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Window Treatments & Hardware', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Yard, Garden & Outdoor Living', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '20', 'sub_category_name' => 'Other Home & Garden', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Jewelry & Watches */
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Childrens Jewelry', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Engagement & Wedding', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Ethnic, Regional & Tribal', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Fashion Jewelry', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Fine Jewelry', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Handcrafted, Artisan Jewelry', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Jewelry Boxes & Organizers', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Jewelry Design & Repair', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Loose Beads', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Loose Diamonds & Gemstones', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Mens Jewelry', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Vintage & Antique Jewelry', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Watches', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Other Jewelry & Watches', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '21', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Music */
				array('id' => NULL, 'category_id' => '22', 'sub_category_name' => 'Cassettes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '22', 'sub_category_name' => 'CDs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '22', 'sub_category_name' => 'Records', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '22', 'sub_category_name' => 'Other Formats', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '22', 'sub_category_name' => 'Storage & Media Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '22', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Musical Instruments & Gear */
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Accordion & Concertina', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Brass', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Equipment', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Guitar', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Harmonica', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Instruction Books, CDs & Video', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Karaoke Entertainment', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Percussion', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Pianos, Keyboards & Organs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Pro Audio Equipment', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Sheet Music & Song Books', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Stage Lighting & Effects', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'String', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Woodwind', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '23', 'sub_category_name' => 'Other Musical Instruments', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Pet Supplies */
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Backyard Poultry Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Bird Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Cat Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Dog Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Fish & Aquariums', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Horse Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Reptile Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Small Animal Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Pet Memorials & Urns', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '24', 'sub_category_name' => 'Other Pet Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Pottery & Glass */
				array('id' => NULL, 'category_id' => '25', 'sub_category_name' => 'Glass', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '25', 'sub_category_name' => 'Pottery & China', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Real Estate */
				array('id' => NULL, 'category_id' => '26', 'sub_category_name' => 'Commercial', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '26', 'sub_category_name' => 'Land', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '26', 'sub_category_name' => 'Manufactured Homes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '26', 'sub_category_name' => 'Residential', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '26', 'sub_category_name' => 'Timeshares for Sale', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '26', 'sub_category_name' => 'Other Real Estate', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Specialty Services */
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Artistic Services', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Custom Clothing & Jewelry', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'eBay Auction Services', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Graphic & Logo Design', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Home Improvement Services', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Item Based Services', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Media Editing & Duplication', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Printing & Personalization', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Restoration & Repair', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Web & Computer Services', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '27', 'sub_category_name' => 'Other Specialty Services', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Sporting Goods */
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Boxing, Martial Arts & MMA', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Cycling', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Fishing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Fitness, Running & Yoga', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Golf', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Hunting', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Indoor Games', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Outdoor Sports', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Team Sports', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Tennis & Racquet Sports', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Water Sports', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Winter Sports', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Other Sporting Goods', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '28', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Sports Mem, Cards & Fan Shop */
				array('id' => NULL, 'category_id' => '29', 'sub_category_name' => 'Autographs-Original', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '29', 'sub_category_name' => 'Autographs-Reprints', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '29', 'sub_category_name' => 'Cards', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '29', 'sub_category_name' => 'Fan Apparel & Souvenirs', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '29', 'sub_category_name' => 'Game Used Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '29', 'sub_category_name' => 'Manufacturer Authenticated', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '29', 'sub_category_name' => 'Vintage Sports Memorabilia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '29', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Stamps */
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'United States', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Canada', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Great Britain', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Africa', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Asia', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Australia & Oceania', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'British Colonies & Territories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Caribbean', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Europe', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Latin America', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Middle East', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Worldwide', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Topical Stamps', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Specialty Philately', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Publications & Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '30', 'sub_category_name' => 'Other Stamps', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Tickets & Experiences */
				array('id' => NULL, 'category_id' => '31', 'sub_category_name' => 'Sports Tickets', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '31', 'sub_category_name' => 'Concert Tickets', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '31', 'sub_category_name' => 'Theater Tickets', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '31', 'sub_category_name' => 'Theme Park & Club Passes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '31', 'sub_category_name' => 'Parking Passes', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '31', 'sub_category_name' => 'Special Experiences', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '31', 'sub_category_name' => 'Other Tickets & Experiences', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Toys & Hobbies */
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Action Figures', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Beanbag Plush', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Building Toys', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Classic Toys', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Diecast & Toy Vehicles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Educational', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Electronic, Battery & Wind-Up', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Fast Food & Cereal Premiums', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Games', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Marbles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Model Railroads & Trains', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Models & Kits', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Outdoor Toys & Structures', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Preschool Toys & Pretend Play', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Puzzles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Radio Control & Control Line', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Robots, Monsters & Space Toys', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Slot Cars', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Stuffed Animals', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Toy Soldiers', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Trading Card Games', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'TV, Movie & Character Toys', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Vintage & Antique Toys', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '32', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Travel */
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Airline', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Campground & RV Parks', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Other', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Car Rental', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Cruises', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Lodging', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Luggage', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Luggage Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Maps', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Rail', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Travel Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Vacation Packages', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '33', 'sub_category_name' => 'Other Travel', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Video Games & Consoles */
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Video Games', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Video Game Consoles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Video Game Accessories', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Prepaid Gaming Cards', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Replacement Parts & Tools', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Strategy Guides & Cheats', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Video Gaming Merchandise', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Other Video Games & Consoles', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '34', 'sub_category_name' => 'Wholesale Lots', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				/* Everything Else */
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Adult Only', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Career Development & Education', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'eBay Special Offers', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'eBay User Tools', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Funeral & Cemetery', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Genealogy', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Information Products', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Metaphysical', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Personal Development', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Personal Security', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Religious Products & Supplies', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Reward Points & Incentives', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Weird Stuff', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Every Other Thing', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'category_id' => '35', 'sub_category_name' => 'Test Auctions', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
		));

		DB::table('conditions')->insert(array(
				array('id' => NULL, 'condition_name' => 'New', 'condition_description' => 'A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag. See the sellers listing for full details.', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'condition_name' => 'New other (see details)', 'condition_description' => 'A new, unused item with absolutely no signs of wear. The item may be missing the original packaging, or in the original packaging but not sealed. The item may be a factory second or a new, unused item with defects. See the sellers listing for full details and description of any imperfections.', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'condition_name' => 'Manufacturer refurbished ', 'condition_description' => 'An item that has been professionally restored to working order by a manufacturer or manufacturer-approved vendor. This means the product has been inspected, cleaned, and repaired to meet manufacturer specifications and is in excellent condition. This item may or may not be in the original packaging. See the sellers listing for full details.', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'condition_name' => 'Seller refurbished ', 'condition_description' => 'An item that has been restored to working order by the eBay seller or a third party not approved by the manufacturer. This means the item has been inspected, cleaned, and repaired to full working order and is in excellent condition. This item may or may not be in original packaging. See the sellers listing for full details.', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'condition_name' => 'Used ', 'condition_description' => 'An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used. See the sellers listing for full details and description of any imperfections.', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'condition_name' => 'For parts or not working ', 'condition_description' => 'An item that does not function as intended and is not fully operational. This includes items that are defective in ways that render them difficult to use, items that require service or repair, or items missing essential components. See the sellers listing for full details.', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
		));

		DB::table('sale_types')->insert(array(
				array('id' => NULL, 'code' => 'f1db2dcda8ad492cc6598a30b9e73dfa', 'name' => 'Auction', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
				array('id' => NULL, 'code' => '232ace077993c3d50785921ec3b1cb85', 'name' => 'Buy It Now', 'created_at' => date("Y-m-d h:i:s"), 'updated_at' => date("Y-m-d h:i:s") ),
		));

	}
}